server.port=8080
spring.application.name=microservicio-socios

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cooperativa_socios
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# Habilitar logging para DataLoader
logging.level.com.cooperativa.socios.loader.DataLoader=INFO
logging.level.org.springframework.boot.CommandLineRunner=INFO

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Custom Exchanges & Queues
custom.rabbitmq.exchange=cooperativa.exchange

# Queues (Colas)
custom.rabbitmq.queue.socio-validacion=q.socios.validacion
custom.rabbitmq.queue.validar-cuentas=q.cuentas.validacion
custom.rabbitmq.queue.validar-prestamo=q.cuentas.prestamos

# Routing Keys (Llaves de ruta)
custom.rabbitmq.routing-key.socio-validacion=socio.validar
custom.rabbitmq.routing-key.validar-cuentas=cuentas.validar.eliminacion
custom.rabbitmq.routing-key.validar-prestamo=cuentas.validar.prestamo


